### ISSUE TITLE
Please add `nextReleaseTime` to `event TrustReleased`

### ISSUE THREAD

**Issue by rok4f** [detrust-finance/protocol_v1#8]
Subgraph needs it.

**Comment by AndyChenW** [comment]
the trust list returned by https://github.com/detrust-finance/protocol_v1/blob/main/contracts/DeTrust.sol#L64 can get this?

**Comment by rok4f** [comment]
Needs it in the event to update the subgraph

**Comment by AndyChenW** [comment]
got it, would you mind to submit a pr for that?

**Comment by rok4f** [comment]
PR: https://github.com/detrust-finance/protocol_v1/pull/9
